version: "3.9"
name: "round"

services:
  bot:
    build: ./bot
    restart: unless-stopped
    depends_on:
      - cache
      - postgres
    links:
      - cache
      - postgres
    volumes:
      - "./bot/app/data:/code/app/data"

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 256128
      POSTGRES_USER: postgres
      POSTGRES_DB: round
    expose:
      - 5432
    volumes:
      - "postgres:/data/db"

  cache:
    image: redis:alpine
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - "cache:/data/cache"

  webapp:
    build: ./webapp
    restart: unless-stopped
    ports:
      - "3015:3000"

volumes:
  cache:
  postgres:
